name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
env: 
  VARIABLE: moja-zmienna

jobs:
 test:
  name: test
  runs-on:  ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 17.0.1
    - run: npm ci
    - run: npm run start